In [29]:
from snowflake.snowpark.context import get_active_session
from snowflake.snowpark.functions import col, avg, count, when, sum
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
from snowflake.ml.data.data_connector import DataConnector

from snowflake.snowpark import Session
from credentials import params

from snowflake.snowpark.types import (
    IntegerType,
    LongType,
    FloatType,
    DoubleType,
    DecimalType,
    StringType
)

from snowflake.ml.registry import Registry

session = Session.builder.configs(params).create()

In [30]:
#df_sp = session.table("HOUSING_PRICE_PROJECT.STAGING_LAYER.RAW_DATA")
#df = df_sp.to_pandas()

X_train_sp = session.table("HOUSING_PRICE_PROJECT.ML_LAYER.TRAIN_SET")
X_train_pd = X_train_sp.to_pandas()

#X_test_sp = session.table("HOUSING_PRICE_PROJECT.ML_LAYER.TEST_SET")
#X_test = X_test_sp.to_pandas()

In [31]:
session.use_database("HOUSING_PRICE_PROJECT")
session.use_schema("ML_LAYER")

# Hyperparameter Tuning

In [33]:
from snowflake.ml.jobs import remote

from ML_hyperp_tune_func1 import dataset_map_creator
from ML_hyperp_tune_func2 import best_hyperparam

In [34]:
session.use_database("HOUSING_PRICE_PROJECT")
session.use_schema("ML_LAYER")

@remote(
    "ml_job_computerpool",
    stage_name="HOUSING_PRICE_PROJECT.ML_LAYER.MLJOBS_STAGE",
    session=session,
    target_instances=4,
    imports=[
        "ML_hyperp_tune_func1.py",
        "ML_hyperp_tune_func2.py"
    ]
)
def hyperparam_tuning(train_name):
    from ML_hyperp_tune_func1 import dataset_map_creator
    from ML_hyperp_tune_func2 import best_hyperparam
    
    from ray import tune
    from snowflake.ml.data.data_connector import DataConnector
    from snowflake.ml.modeling.distributors.xgboost.xgboost_estimator import XGBScalingConfig
    from snowflake.ml.runtime_cluster import scale_cluster
    from snowflake.ml.modeling.tune import get_tuner_context
    from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
    from snowflake.ml.modeling.distributors.xgboost.xgboost_estimator import XGBEstimator   
    from snowflake.ml.modeling.tune import (Tuner, TunerConfig, get_tuner_context) 
    from snowflake.snowpark.types import StringType


    # SESSION, DATASET AND FEATURE LIST ************************************************************************
    job_session = get_active_session()
    print("librerie importate + session activated *********************************")
 
    train_tab = job_session.table(train_name)
    #train_tab = train_tab.drop('"property_id"', '"price_category"', 'SOURCE_FILE') # <--- REMOVED ON 29/08
    
    #train_tab = X_train
    
    #for column in train_tab.columns:                                               # <--- REMOVED ON 29/08
    #    train_tab = train_tab.with_column_renamed(column, col.replace('"', ''))
    
    print("train_tab importato *********************************")
    
    
    # DATASET_MAP CREATION USING EXTERNAL FUNCTION **************************************************************
    # PREPROCESSING HAPPENS WITHIN THIS FUNCTION !! *************************************************************
    dataset_map, features, preproc_model_version = dataset_map_creator(job_session, train_tab, size_tuning_df = 15_000, k_cv = 3) 
                                                  #dataset_map_creator(train_tab, job_session)
                                
    print("dataset_map e features ritornate *********************************")

    #CREATING FEATURE LIST **************************************************************************************
    #features = train_tab_prepr.columns
    #features.remove('PRICE_IN_LAKHS')
    # FEATURES RETURNED BY dataset_map_creator()


    

    # SEARCH SPACE *********************************************************************************************
    search_space = {
        "max_depth": tune.choice([3]), #[3, 6, 9], during development it was = 2
        "learning_rate": tune.choice([0.1]), #[0.01, 0.05, 0.1], , during development it was = 0.05
        "n_estimators": tune.choice([4]), #[100, 200, 300] , during development it was = 3
    }
    print("search space defined *********************************")

    #TUNER CONFIG **********************************************************************************************
    tuner_config = TunerConfig(
        metric="rmse_valid_avg",
        mode="min",
        num_trials=1,
        uses_snowflake_trainer=True,
        max_concurrent_trials=5
    )
    print("tuner config defined *********************************")

    #TRAIN FUNC DEFINITION **************************************************************************************
    def train_func():
    
        ctx = get_tuner_context()
    
        hyper_params = ctx.get_hyper_params()
        datasets = ctx.get_dataset_map()
    
        print("hyperparam and dataset retrieved from context *********************************")

        print(f"hyper_params[max_depth] = {hyper_params["max_depth"]}, type = {type(hyper_params["max_depth"])}")
        print(f"hyper_params[learning_rate] = {hyper_params["learning_rate"]}, type = {type(hyper_params["learning_rate"])}")
        print(f"hyper_params[n_estimators] = {hyper_params["n_estimators"]}, type = {type(hyper_params["n_estimators"])}")
        
        ###################################################################################################################

        rmse_train_list = []
        mae_train_list = []
        r2_train_list = []
        
        rmse_valid_list = []
        mae_valid_list = []
        r2_valid_list = []
        
        for i in range(int(len(datasets)/2)):
            train_connector = datasets[f"train_{i}"]
            valid_connector = datasets[f"valid_{i}"]
        
            estimator = XGBEstimator(
                params={
                    "max_depth": hyper_params["max_depth"],
                    "learning_rate": hyper_params["learning_rate"],
                },
                n_estimators=hyper_params["n_estimators"],
                objective="reg:squarederror",
                scaling_config=XGBScalingConfig(
                    num_workers=1
                )
            )
            print(f"estimator created, ciclo {i} *********************************")

            
            estimator.fit(
                dataset=train_connector,
                input_cols=features,
                label_col='PRICE_IN_LAKHS'
            )
    
            print(f"estimator trained, ciclo {i} *********************************")

            
            train_conn_pd = train_connector.to_pandas()
            X_train_pd = train_conn_pd.drop(['PRICE_IN_LAKHS'], axis = 1)
            target_train = train_conn_pd['PRICE_IN_LAKHS']

            valid_conn_pd = valid_connector.to_pandas()
            X_valid_pd = valid_conn_pd.drop(['PRICE_IN_LAKHS'], axis = 1)
            target_valid = valid_conn_pd['PRICE_IN_LAKHS']
    
            print(f"pandas dataframe created, ciclo {i} *********************************")
    
            predictions_train = estimator.predict(X_train_pd)
               
            rmse_train = mean_squared_error(
                y_true = target_train,
                y_pred = predictions_train
            )

            mae_train = mean_absolute_error(
                y_true = target_train,
                y_pred = predictions_train
            )
        
            r2_train = r2_score(
                y_true = target_train,
                y_pred = predictions_train
            )
            
            rmse_train_list.append(rmse_train)
            mae_train_list.append(mae_train)
            r2_train_list.append(r2_train)
            
            print(f"rmse_train_{i} = {rmse_train} *********************************")
            
            predictions_valid = estimator.predict(X_valid_pd)
               
            rmse_valid = mean_squared_error(
                y_true = target_valid,
                y_pred = predictions_valid
            )

            mae_valid = mean_absolute_error(
                y_true = target_valid,
                y_pred = predictions_valid
            )
        
            r2_valid = r2_score(
                y_true = target_valid,
                y_pred = predictions_valid
            )

            rmse_valid_list.append(rmse_valid)
            mae_valid_list.append(mae_valid)
            r2_valid_list.append(r2_valid)
            
            print(f"rmse_valid_{i} = {rmse_valid} *********************************")
        

        print("\nrmse_train (average) = ", np.mean(rmse_train_list))
        print("\nrmse_valid (average) = ", np.mean(rmse_valid_list))

        ###################################################################################################################
        
        rmse_train_avg = np.mean(rmse_train_list)
        rmse_valid_avg = np.mean(rmse_valid_list)

        mae_train_avg = np.mean(mae_train_list)
        mae_valid_avg = np.mean(mae_valid_list)

        r2_train_avg = np.mean(r2_train_list)
        r2_valid_avg = np.mean(r2_valid_list)
        
        ctx.report(
            metrics={
                "rmse_valid": rmse_valid_list, 
                "rmse_train": rmse_train_list,
                "rmse_train_avg":  rmse_train_avg,
                "rmse_valid_avg": rmse_valid_avg,
                "mae_train_avg": mae_train_avg,
                "mae_valid_avg": mae_valid_avg,
                "r2_train_avg": r2_train_avg,
                "r2_valid_avg": r2_valid_avg
            },
            model=estimator
        )
        print("\nctx.report ok *********************************")

    #TUNER DECLARATION ******************************************************************************************
    tuner = Tuner(
        train_func=train_func,
        search_space=search_space,
        tuner_config=tuner_config
    )
    print("\ntuner declaration done *********************************")
    
    #RUN THE TUNER ******************************************************************************************     

    results = tuner.run(dataset_map = dataset_map)
        
    print("\nsembrerebbe essere arrivato fino alla fine *********************************")

    res = results.results
    
    print(type(res), end = "\n\n")
    res_cols = list(res.columns)
    print(res_cols, end = "\n\n")
    print(res.info(), end = "\n\n")
    print(res["rmse_train"], end = "\n\n")
    print(res["rmse_valid"], end = "\n\n")

    #best_hyperparam(res, preproc_model_version, job_session)
    best_hyperparam(job_session, res, preproc_model_version, gap_max = 100)

In [35]:
import time
start = time.time()

job = hyperparam_tuning("HOUSING_PRICE_PROJECT.ML_LAYER.TRAIN_SET") 
job.wait()

end = time.time()

print(job.status)
print(f"{(end - start) / 60 :.2f} min")

DONE
1.73 min

In [36]:
job.show_logs(verbose=True)

2026-08-29T18:47:40.161Z	info	otelconftelemetry/tracer.go:47	Internal trace telemetry disabled	{"resource": {"service.instance.id": "c5f610d5-4c5f-4e40-90ff-e5f281f91224", "service.name": "otelcol-contrib", "service.version": "0.156.0"}}
2026-08-29T18:47:40.162Z	warn	builders/builders.go:40	"otlp" alias is deprecated; use "otlp_grpc" instead	{"resource": {"service.instance.id": "c5f610d5-4c5f-4e40-90ff-e5f281f91224", "service.name": "otelcol-contrib", "service.version": "0.156.0"}, "otelcol.component.id": "otlp", "otelcol.component.kind": "exporter", "otelcol.signal": "metrics"}
2026-08-29T18:47:40.180Z	info	service@v0.156.0/service.go:256	Starting otelcol-contrib...	{"resource": {"service.instance.id": "c5f610d5-4c5f-4e40-90ff-e5f281f91224", "service.name": "otelcol-contrib", "service.version": "0.156.0"}, "Version": "0.156.0", "NumCPU": 8}
2026-08-29T18:47:40.180Z	info	extensions/extensions.go:41	Starting extensions...	{"resource": {"service.instance.id": "c5f610d5-4c5f-4e40-90ff-e5f281f91224", "service.name": "otelcol-contrib", "service.version": "0.156.0"}}
2026-08-29T18:47:40.180Z	info	service@v0.156.0/service.go:279	Everything is ready. Begin running and processing data.	{"resource": {"service.instance.id": "c5f610d5-4c5f-4e40-90ff-e5f281f91224", "service.name": "otelcol-contrib", "service.version": "0.156.0"}}
Metric sent (UDP, best-effort) to 127.0.0.1:8125: mljob.job_payload_source:1|c|#source:stage
Installing system packages from /mnt/job_stage/system/requirements.txt
Looking in links: /opt/wheels
Requirement already satisfied: cloudpickle~=3.0 in /opt/python/cpython-3.12.12-linux-x86_64-gnu/lib/python3.12/site-packages (from -r /mnt/job_stage/system/requirements.txt (line 1)) (3.1.1)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager, possibly rendering your system unusable. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv. Use the --root-user-action option if you know what you are doing and want to suppress this warning.
System package installation completed in 1 seconds
Metric sent (UDP, best-effort) to 127.0.0.1:8125: mljob.system_pip_install_seconds:1|h
2026-08-29 18:47:43,560 - INFO - AST state has not been set explicitly. Defaulting to ast_enabled = True.
2026-08-29 18:47:47,905 - INFO - Snowflake Connector for Python Version: 4.7.2, Python Version: 3.12.12, Platform: Linux-5.15.206-14.2026072814gcc150e5+snow+aws+5.15+amd64.x86_64-x86_64-with-glibc2.39
2026-08-29 18:47:47,905 - INFO - Connecting to GLOBAL Snowflake domain
2026-08-29 18:47:51,389 - INFO - Snowpark Session information:
"version" : 1.54.0,
"python.version" : 3.12.12,
"python.connector.version" : 4.7.2,
"python.connector.session.id" : 13202278500900970,
"os.name" : Linux

2026-08-29 18:47:51,529 - INFO - Closing session: 13202278500900970
2026-08-29 18:47:51,529 - INFO - Canceling all running queries
2026-08-29 18:47:51,744 - INFO - Closed session: 13202278500900970
Head Instance: index=0 ip=10.244.36.204 status=READY
NODE_TYPE=head RAY_HEAD_ADDRESS=10.244.36.204:12001
Creating log directories...
Metric sent (UDP, best-effort) to 127.0.0.1:8125: mljob.startup_total_seconds:11|h
Running command: python /opt/mljob/mljob_launcher.py /mnt/job_stage/app/func.py --script_main_func func --function_args={"kind": "base", "value": [["HOUSING_PRICE_PROJECT.ML_LAYER.TRAIN_SET"], {}], "protocol": null, "serialize_error": null}
Shared memory size: 8589934592 bytes
Dashboard enabled: true
Prometheus started successfully
time=2026-08-29T18:47:51.943Z level=INFO source=main.go:1730 msg="updated GOGC" old=100 new=75
time=2026-08-29T18:47:51.944Z level=INFO source=main.go:789 msg="Updating GOMAXPROCS=6: determined from CPU quota" component=automaxprocs
time=2026-08-29T18:47:51.944Z level=INFO source=memlimit.go:198 msg="GOMEMLIMIT is updated" component=automemlimit package=github.com/KimMachineGun/automemlimit/memlimit GOMEMLIMIT=29805790003 previous=9223372036854775807
time=2026-08-29T18:47:51.944Z level=INFO source=main.go:896 msg="Starting Prometheus Server" mode=server version="(version=3.13.2, branch=HEAD, revision=bb5dff00cf8fdfbf5c65e0531aa835fa238a43a2)"
time=2026-08-29T18:47:51.944Z level=INFO source=main.go:901 msg="operational information" build_context="(go=go1.26.5, platform=linux/amd64, user=root@56a9973e8bdd, date=20260730-11:31:39, tags=netgo,builtinassets)" host_details="(Linux 5.15.206-14.2026072814gcc150e5+snow+aws+5.15+amd64.x86_64 #1 SMP Tue Jul 28 15:09:39 UTC 2026 x86_64 job-0 (none))" fd_limits="(soft=1048576, hard=1048576)" vm_limits="(soft=unlimited, hard=unlimited)"
time=2026-08-29T18:47:52.101Z level=INFO source=web.go:727 msg="Start listening for connections" component=web address=0.0.0.0:9091
time=2026-08-29T18:47:52.101Z level=INFO source=main.go:1462 msg="Starting TSDB ..."
time=2026-08-29T18:47:52.103Z level=INFO source=tls_config.go:354 msg="Listening on" component=web address=[::]:9091
time=2026-08-29T18:47:52.103Z level=INFO source=tls_config.go:357 msg="TLS is disabled." component=web http2=false address=[::]:9091
time=2026-08-29T18:47:52.104Z level=INFO source=head.go:709 msg="Replaying on-disk memory mappable chunks if any" component=tsdb
time=2026-08-29T18:47:52.104Z level=INFO source=head.go:795 msg="On-disk memory mappable chunks replay completed" component=tsdb duration=1.095µs
time=2026-08-29T18:47:52.104Z level=INFO source=head.go:803 msg="Replaying WAL, this may take a while" component=tsdb
time=2026-08-29T18:47:52.104Z level=INFO source=head.go:898 msg="WAL segment loaded" component=tsdb segment=0 maxSegment=0 duration=120.733µs
time=2026-08-29T18:47:52.104Z level=INFO source=head.go:935 msg="WAL replay completed" component=tsdb checkpoint_replay_duration=22.876µs wal_replay_duration=142.2µs wbl_replay_duration=170ns chunk_snapshot_load_duration=0s mmap_chunk_replay_duration=1.095µs total_replay_duration=186.637µs
time=2026-08-29T18:47:52.105Z level=INFO source=main.go:1483 msg="filesystem information" fs_type=OVERLAYFS_SUPER_MAGIC
time=2026-08-29T18:47:52.105Z level=INFO source=main.go:1486 msg="TSDB started"
time=2026-08-29T18:47:52.105Z level=INFO source=main.go:1684 msg="Loading configuration file" filename=/opt/prometheus/prometheus.yml
time=2026-08-29T18:47:52.105Z level=INFO source=main.go:1100 msg="TSDB retention updated" duration=0s size=2GiB percentage=0
time=2026-08-29T18:47:52.105Z level=INFO source=main.go:1723 msg="Completed loading of configuration file" db_storage=21.392µs remote_storage=1.291µs web_handler=224ns query_engine=510ns scrape=175.584µs scrape_sd=35.702µs notify=1.248µs notify_sd=677ns rules=1.564µs tracing=6.922µs filename=/opt/prometheus/prometheus.yml totalDuration=475.303µs
time=2026-08-29T18:47:52.105Z level=INFO source=main.go:1447 msg="Server is ready to receive web requests."
time=2026-08-29T18:47:52.106Z level=INFO source=manager.go:211 msg="Starting rule manager..." component="rule manager"
time=2026-08-29T18:47:52.106Z level=ERROR source=file.go:233 msg="Error adding file watch" component="discovery manager scrape" discovery=file config=ray path=/tmp/ray/ err="no such file or directory"
2026-08-29 18:47:54,202 - INFO - Snowflake Connector for Python Version: 4.7.2, Python Version: 3.12.12, Platform: Linux-5.15.206-14.2026072814gcc150e5+snow+aws+5.15+amd64.x86_64-x86_64-with-glibc2.39
2026-08-29 18:47:54,203 - INFO - Connecting to GLOBAL Snowflake domain
2026-08-29 18:47:56,483 - INFO - Snowpark Session information:
"version" : 1.54.0,
"python.version" : 3.12.12,
"python.connector.version" : 4.7.2,
"python.connector.session.id" : 13202278500761850,
"os.name" : Linux

2026-08-29 18:48:00,469	INFO worker.py:1672 -- Using address 10.244.36.204:12001 set in the environment variable RAY_ADDRESS
2026-08-29 18:48:00,472	INFO worker.py:1814 -- Connecting to existing Ray cluster at address: 10.244.36.204:12001...
2026-08-29 18:48:01,008	WARNING services.py:2213 -- WARNING: The object store is using /tmp/ray instead of /dev/shm because /dev/shm has only 8589934592 bytes available. This will harm performance! You may be able to free up space by deleting files in /dev/shm. If you are inside a Docker container, you can increase /dev/shm size by passing '--shm-size=9.13gb' to 'docker run' (or add it to the run_options list in a Ray cluster config). Make sure to set this to more than 30% of available RAM.
2026-08-29 18:47:54,406	INFO usage_lib.py:448 -- Usage stats collection is disabled.
2026-08-29 18:47:54,407	INFO scripts.py:940 -- Local node IP: 10.244.36.204
2026-08-29 18:48:04,144	SUCC scripts.py:979 -- --------------------
2026-08-29 18:48:04,144	SUCC scripts.py:980 -- Ray runtime started.
2026-08-29 18:48:04,144	SUCC scripts.py:981 -- --------------------
2026-08-29 18:48:04,144	INFO scripts.py:983 -- Next steps
2026-08-29 18:48:04,144	INFO scripts.py:986 -- To add another node to this Ray cluster, run
2026-08-29 18:48:04,144	INFO scripts.py:989 --   ray start --address='10.244.36.204:12001'
2026-08-29 18:48:04,144	INFO scripts.py:1000 -- To connect to this Ray cluster:
2026-08-29 18:48:04,144	INFO scripts.py:1002 -- import ray
2026-08-29 18:48:04,144	INFO scripts.py:1003 -- ray.init(_node_ip_address='10.244.36.204')
2026-08-29 18:48:04,145	INFO scripts.py:1017 -- To submit a Ray job using the Ray Jobs CLI:
2026-08-29 18:48:04,145	INFO scripts.py:1018 --   RAY_API_SERVER_ADDRESS='http://10.244.36.204:12003' ray job submit --working-dir . -- python my_script.py
2026-08-29 18:48:04,145	INFO scripts.py:1027 -- See https://docs.ray.io/en/latest/cluster/running-applications/job-submission/index.html
2026-08-29 18:48:04,145	INFO scripts.py:1031 -- for more information on submitting Ray jobs to the Ray cluster.
2026-08-29 18:48:04,145	INFO scripts.py:1036 -- To terminate the Ray runtime, run
2026-08-29 18:48:04,145	INFO scripts.py:1037 --   ray stop
2026-08-29 18:48:04,145	INFO scripts.py:1040 -- To view the status of the cluster, use
2026-08-29 18:48:04,145	INFO scripts.py:1041 --   ray status
2026-08-29 18:48:04,145	INFO scripts.py:1045 -- To monitor and debug Ray, view the dashboard at
2026-08-29 18:48:04,145	INFO scripts.py:1046 --   10.244.36.204:12003
2026-08-29 18:48:04,145	INFO scripts.py:1053 -- If connection to the dashboard fails, check your firewall settings and network configuration.
Patching Grafana datasource configuration to use port 9091
Grafana started successfully
Metric sent (UDP, best-effort) to 127.0.0.1:8125: mljob.ray_startup_seconds:13|h
Metric sent (UDP, best-effort) to 127.0.0.1:8125: mljob.startup_status:1|c|#status:success
2026-08-29 18:48:04,491	INFO worker.py:2012 -- Connected to Ray cluster.
Grafana server is running with elevated privileges. This is not recommended
/opt/python/cpython-3.12.12-linux-x86_64-gnu/lib/python3.12/site-packages/ray/_private/worker.py:2051: FutureWarning: Tip: In future versions of Ray, Ray will no longer override accelerator visible devices env var if num_gpus=0 or num_gpus=None (default). To enable this behavior and turn off this error message, set RAY_ACCEL_ENV_VAR_OVERRIDE_ON_ZERO=0
  warnings.warn(
2026-08-29 18:48:06,757 - INFO - Waiting for instances to be ready (min_instances=4, target_instances=4, min_wait_time=6.0s, timeout=720.0s, max_check_interval=10.0s)
2026-08-29 18:48:06,757 - INFO - Target instance requirement met: 4 instances available after 0.0s
Metric sent (UDP, best-effort) to 127.0.0.1:8125: mljob.cluster_formation_seconds:0.0006649494171142578|h
logger=migrator t=2026-08-29T18:48:06.947931619Z level=warn msg="Skipping migration: Already executed, but not recorded in migration log" id="drop unique orgID index on alert_configuration if exists"
--------------------------------
ML job started
--------------------------------
logger=migrator t=2026-08-29T18:48:07.504565741Z level=warn msg="Skipping migration: Already executed, but not recorded in migration log" id="drop index UQE_dashboard_public_config_uid - v1"
logger=migrator t=2026-08-29T18:48:07.509485151Z level=warn msg="Skipping migration: Already executed, but not recorded in migration log" id="drop index IDX_dashboard_public_config_org_id_dashboard_uid - v1"
logger=migrator t=2026-08-29T18:48:07.654410216Z level=warn msg="Skipping migration: Already executed, but not recorded in migration log" id="drop my_row_id and add primary key to file table if my_row_id exists (auto-generated mysql column)"
logger=migrator t=2026-08-29T18:48:07.679072528Z level=warn msg="Skipping migration: Already executed, but not recorded in migration log" id="drop my_row_id and add primary key to file_meta table if my_row_id exists (auto-generated mysql column)"
logger=migrator t=2026-08-29T18:48:08.35179442Z level=warn msg="Skipping migration: Already executed, but not recorded in migration log" id="drop my_row_id and add primary key with columns snapshot_uid,resource_type,partition_number to table cloud_migration_snapshot_partition if my_row_id exists (auto-generated mysql column)"
logger=renderer.manager t=2026-08-29T18:48:08.767000322Z level=error msg="Failed to get renderer plugin sources" error="failed to open plugins path"
logger=plugin.sources t=2026-08-29T18:48:08.768231952Z level=error msg="Failed to load external plugins" error="failed to open plugins path"
logger=secret-migrator t=2026-08-29T18:48:09.063811474Z level=warn msg="Skipping migration: Already executed, but not recorded in migration log" id="drop my_row_id and add primary key with columns namespace,name,version to table secret_encrypted_value if my_row_id exists (auto-generated mysql column)"
logger=resource-migrator t=2026-08-29T18:48:09.275644609Z level=warn msg="Skipping migration: Already executed, but not recorded in migration log" id="drop my_row_id and add primary key with columns group,resource to table resource_version if my_row_id exists (auto-generated mysql column)"
logger=storage.unified.migrations t=2026-08-29T18:48:09.332850076Z level=warn msg="Failed to check if migration exists" migration=folders-dashboards error="failed to check migration existence: SQL logic error: no such table: unifiedstorage_migration_log (1)"
logger=storage.unified.migrations t=2026-08-29T18:48:09.332982319Z level=warn msg="Failed to check if migration exists" migration=folders-dashboards error="failed to check migration existence: SQL logic error: no such table: unifiedstorage_migration_log (1)"
2026-08-29 18:48:10,040 - INFO - generated new fontManager
--------------------------------
ML job finished
--------------------------------
Metric sent (UDP, best-effort) to 127.0.0.1:8125: mljob.user_payload_seconds:3.5771734714508057|h
2026-08-29 18:48:10,647 - INFO - Closing session: 13202278500761850
2026-08-29 18:48:10,647 - INFO - Canceling all running queries
2026-08-29 18:48:10,838 - INFO - Closed session: 13202278500761850
2026-08-29 18:48:10,842 - INFO - Signaling workers to shut down...
2026-08-29 18:48:10,843	INFO worker.py:1672 -- Using address 10.244.36.204:12001 set in the environment variable RAY_ADDRESS
2026-08-29 18:48:10,843	INFO worker.py:1814 -- Connecting to existing Ray cluster at address: 10.244.36.204:12001...
2026-08-29 18:48:10,843	INFO worker.py:1828 -- Calling ray.init() again after it has already been called.
2026-08-29 18:48:10,844 - INFO - Found 3 worker nodes
2026-08-29 18:48:10,844 - INFO - Creating new shutdown signal actor: Failed to look up actor with name 'ShutdownSignal'. This could because 1. You are trying to look up a named actor you didn't create. 2. The named actor died. 3. You did not use a namespace matching the namespace of the actor.
2026-08-29 18:48:13,582 - INFO - Shutdown requested: {'status': 'shutdown_requested', 'timestamp': 1788029293.5816507, 'host': 'job-0'}
2026-08-29 18:48:13,582 - INFO - Waiting up to 15s for workers to acknowledge shutdown signal...
logger=provisioning.plugins t=2026-08-29T18:48:14.767169073Z level=error msg="Failed to read plugin provisioning files from directory" path=/tmp/ray/session_latest/metrics/grafana/provisioning/plugins error="open /tmp/ray/session_latest/metrics/grafana/provisioning/plugins: no such file or directory"
logger=provisioning.alerting t=2026-08-29T18:48:14.767216356Z level=error msg="can't read alerting provisioning files from directory" path=/tmp/ray/session_latest/metrics/grafana/provisioning/alerting error="open /tmp/ray/session_latest/metrics/grafana/provisioning/alerting: no such file or directory"
logger=plugin.backgroundinstaller t=2026-08-29T18:48:14.773649356Z level=error msg="Failed to install plugin" pluginId=grafana-exploretraces-app version= error="Get \"https://grafana.com/api/plugins/grafana-exploretraces-app/versions\": dial tcp: lookup grafana.com on 169.254.20.10:53: no such host"
logger=plugin.backgroundinstaller t=2026-08-29T18:48:14.789717576Z level=error msg="Failed to install plugin" pluginId=grafana-metricsdrilldown-app version= error="Get \"https://grafana.com/api/plugins/grafana-metricsdrilldown-app/versions\": dial tcp: lookup grafana.com on 169.254.20.10:53: no such host"
logger=plugin.backgroundinstaller t=2026-08-29T18:48:14.806529007Z level=error msg="Failed to install plugin" pluginId=grafana-lokiexplore-app version= error="Get \"https://grafana.com/api/plugins/grafana-lokiexplore-app/versions\": dial tcp: lookup grafana.com on 169.254.20.10:53: no such host"
logger=plugin.backgroundinstaller t=2026-08-29T18:48:14.822033786Z level=error msg="Failed to install plugin" pluginId=grafana-pyroscope-app version= error="Get \"https://grafana.com/api/plugins/grafana-pyroscope-app/versions\": dial tcp: lookup grafana.com on 169.254.20.10:53: no such host"
logger=renderer.manager t=2026-08-29T18:48:15.065941006Z level=error msg="Failed to get renderer plugin sources" error="failed to open plugins path"
logger=grafana.update.checker t=2026-08-29T18:48:15.089820157Z level=error msg="Update check failed" error="failed to get stable version from grafana.com: Get \"https://grafana.com/api/grafana/versions/stable\": dial tcp: lookup grafana.com on 169.254.20.10:53: no such host" duration=23.962572ms
logger=plugin.signature.key_retriever t=2026-08-29T18:48:15.089826853Z level=error msg="Error downloading plugin manifest keys" error="Get \"https://grafana.com/api/plugins/ci/keys\": dial tcp: lookup grafana.com on 169.254.20.10:53: no such host"
logger=plugin.angulardetectorsprovider.dynamic t=2026-08-29T18:48:15.11275763Z level=error msg="Error while updating detectors" error="fetch: http do: Get \"https://grafana.com/api/plugins/angular_patterns\": dial tcp: lookup grafana.com on 169.254.20.10:53: no such host"
2026-08-29 18:48:15,585 - INFO - All 3 workers acknowledged shutdown. Completed in 2.00s
Metric sent (UDP, best-effort) to 127.0.0.1:8125: mljob.worker_shutdown_seconds:4.743112087249756|h
2026-08-29 18:48:16,362 - INFO - Closed session: 13202278500761850
Metric sent (UDP, best-effort) to 127.0.0.1:8125: mljob.job_status:1|c|#status:success
2026-08-29T18:48:19.107Z	info	otelcol@v0.156.0/collector.go:397	Received signal from OS	{"resource": {"service.instance.id": "c5f610d5-4c5f-4e40-90ff-e5f281f91224", "service.name": "otelcol-contrib", "service.version": "0.156.0"}, "signal": "terminated"}
2026-08-29T18:48:19.107Z	info	service@v0.156.0/service.go:293	Starting shutdown...	{"resource": {"service.instance.id": "c5f610d5-4c5f-4e40-90ff-e5f281f91224", "service.name": "otelcol-contrib", "service.version": "0.156.0"}}
2026-08-29T18:48:19.108Z	info	extensions/extensions.go:69	Stopping extensions...	{"resource": {"service.instance.id": "c5f610d5-4c5f-4e40-90ff-e5f281f91224", "service.name": "otelcol-contrib", "service.version": "0.156.0"}}
2026-08-29T18:48:19.108Z	info	service@v0.156.0/service.go:307	Shutdown complete.	{"resource": {"service.instance.id": "c5f610d5-4c5f-4e40-90ff-e5f281f91224", "service.name": "otelcol-contrib", "service.version": "0.156.0"}}
Head node job completed. Exiting.

In [37]:
job.status

'DONE'

# Tuner

In [ ]:
def dataset_map_creator(job_session, data_table, size_tuning_df = 15_000, k_cv = 3)

    from snowflake.snowpark.functions import row_number, random, col
    from snowflake.snowpark.window import Window
    from snowflake.ml.data.data_connector import DataConnector
    
    SIZE_TUNING_DF = size_tuning_df
    K_CV = k_cv
    
    # import the dataset as snowpark dataframe
    df_sp = data_table#job_session.table(data_table)
    
    # take a random sample of SIZE_TUNING_DF rows
    tuning_df = df_sp.sample(n = SIZE_TUNING_DF)
    
    # updating SIZE_TUNING_DF in case df_sp.count() < SIZE_TUNING_DF
    SIZE_TUNING_DF = tuning_df.count()
    
    # save tuning_df as temporary table to avoid that any time tuning_df is called new random rows are taken
    tuning_df.write.mode("overwrite").save_as_table(
        "TEMP_TUNING_DATA",
        table_type="temporary"
    )
    
    # importing tuning_df from the temporary tab
    tuning_tab = job_session.table("TEMP_TUNING_DATA")

    print("tutta la prima parte di tuner() e' ok *********************************")

    
    
    # PREPROCESSING using the pipeline from model registry *******************************************************
    registry = Registry(
        session=job_session,
        database_name="HOUSING_PRICE_PROJECT",
        schema_name="ML_LAYER"
    )
    
    preprocessor_model = registry.get_model("PREPROCESSING_PIPELINE").version("LAST")    
    
    tuning_tab_prepr = preprocessor_model.run(
        tuning_tab,
        function_name="transform"
    )    
 
    # ADJUSTING THE PREPROCESSED DATASET *************************************************************************
    for column in tuning_tab_prepr.columns:
        #if column[0] =='"':
        tuning_tab_prepr = tuning_tab_prepr.with_column_renamed(column, column.replace('"', ''))
    
    cat_cols = [
        field.name
        for field in tuning_tab_prepr.schema.fields
        if isinstance(field.datatype, StringType)    
    ]
    
    tuning_tab_prepr = tuning_tab_prepr.drop(cat_cols)


    # CREATE FEATURE LIST
    features = tuning_tab_prepr.columns
    print(type(features))
    print()
    print(features)
    features.remove('PRICE_IN_LAKHS')

    print("preprocessing, dataset adjustment e feature list creation done! *********************************")


    
    
    # creating "random_numb" column to numerate each row
    window = Window.order_by(random())
    tuning_tab_prepr = tuning_tab_prepr.with_column(
        "RANDOM_NUMB",
        row_number().over(window)
    )
    print("tuner 1 *********************************")
    
    # creating the ranges list, containing ranges on which to filter the dataframe; example: ranges = [(0, 100), (100, 200), ...]
    i = 0
    frac = SIZE_TUNING_DF / K_CV
    
    ranges = []
    for n in range(K_CV):
        j = (i, i + frac)
        ranges.append(j)
        i += frac
    print("tuner 2 *********************************")
    
    # separating the snowpark dataframe in the k folds for the CV
    i = 0
    folds = []

    print(ranges)
    print(type(tuning_tab_prepr))
    
    for low_limit, up_limit in ranges:
        fold = tuning_tab_prepr.filter((col("RANDOM_NUMB") > low_limit) & (col("RANDOM_NUMB") <= up_limit))
        folds.append(fold)
        i += 1
        
    print("tuner 3 *********************************")
    # creating dataset_map with proper fold combinations
    dataset_map = {}

    for validation_idx in range(K_CV):
    
        validation_df = folds[validation_idx]
    
        train_df = None
    
        for i, fold in enumerate(folds):
            if i != validation_idx:
                if train_df is None:
                    train_df = fold
                else:
                    train_df = train_df.union(fold)
        
        dataset_map[f"train_{validation_idx}"] = DataConnector.from_dataframe(train_df.drop("RANDOM_NUMB"))
        dataset_map[f"valid_{validation_idx}"] = DataConnector.from_dataframe(validation_df.drop("RANDOM_NUMB"))
    print("tuner 4 *********************************")
    
    return dataset_map, features, preprocessor_model.version_name

In [ ]:
X_train = session.table("HOUSING_PRICE_PROJECT.ML_LAYER.TRAIN_SET")
#X_train = X_train.drop('"property_id"', '"price_category"', 'SOURCE_FILE')

#for column in X_train.columns:
#    if column[0] =='"':
#        X_train = X_train.with_column_renamed(column, column[1:-1])

In [ ]:
a, b = dataset_map_creator(X_train, session)

In [ ]:
a

In [ ]:
a['train_0'].to_pandas()[['PROPERTY_ID', 'RANDOM_NUMB']].sort_values(by= 'RANDOM_NUMB')

In [ ]:
a['valid_0'].to_pandas()[['PROPERTY_ID', 'RANDOM_NUMB']].sort_values(by= 'RANDOM_NUMB')

# how to choose the best model

In [ ]:
import pandas as pd

res = pd.DataFrame({
    "rmse_train": [
        [7956.8466796875, 7889.2763671875, 8068.8154296875],
        [7856.8466796875, 7789.2763671875, 7968.8154296875],
        [7756.8466796875, 7789.2763671875, 7996.8154296875]
    ],

    "rmse_valid": [
        [9521.8466796875, 9487.2763671875, 9602.8154296875],
        [9856.8466796875, 9789.2763671875, 9468.8154296875],
        [9956.8466796875, 9889.2763671875, 9568.8154296875]
    ],

    "should_checkpoint": [
        True,
        True,
        True
    ],

    "trial_id": [
        "996a3_00000",
        "996a3_00000",
        "996a3_00000"
    ],

    "time_total_s": [
        126.91735076904297,
        126.91735076904297,
        126.91735076904297
    ],

    "config/max_depth": [
        1,
        2,
        3
    ],
    
    "config/learning_rate": [
        0.05,
        0.06,
        0.07
    ],

    "config/n_estimators": [
        3,
        4,
        5
    ],

    "config/min_child_weight": [
        1,
        5,
        10
    ],

    "config/subsample": [
        0.8,
        1.0,
        1.2
    ],    
})

In [ ]:
def best_hyperparam(job_session, res, preproc_model_version, gap_max = 100):
    
    from datetime import datetime
    GAP_MAX = gap_max
    
    # RENAME COLUMNS TO REMOVE "config/" ***************************************************************************
    res.rename(columns = { col : col.replace("config/", "") for col in res.columns }, inplace = True)

    # CREATE NEW COLUMNS AND CALCULATE AVERAGE METRICS **************************************************************
    timestamp = datetime.now()
    res["timestamp"] = timestamp
 
    timestamp_code = timestamp.strftime("%Y%m%d_%H%M%S")
    res["tuning_run_id"] = timestamp_code

    res["preprocessor_version"] = preproc_model_version
    
    #res["rmse_train_avg"] = res["rmse_train"].apply(lambda x: np.mean(x))
    #res["rmse_valid_avg"] = res["rmse_valid"].apply(lambda x: np.mean(x))
    
    res["relative_gap"] = (res["rmse_valid_avg"] - res["rmse_train_avg"])/res["rmse_train_avg"]

    
    # FIND THE RAW WITH BEST METRICS **************************************************************
    rmse_valid_avg_min = res.loc[res.relative_gap < GAP_MAX, "rmse_valid_avg"].min()
    best_raw = res[res["rmse_valid_avg"] == rmse_valid_avg_min]

    print("arriva fino a qui\n")
    print(res.columns)
    

    for data, tab in [(res, "XGBOOST_TUNING_RESULTS"), (best_raw, "XGBOOST_BEST_PARAMETERS")]:
        
        snowpark_df = job_session.create_dataframe(data)

        snowpark_df.write.mode("overwrite").save_as_table(
            "results_to_append",
            table_type="temporary"
        )
        
        print("\nsnowpark_df.columns:\n", snowpark_df.columns)
        
        query = f"""
            INSERT INTO {tab} ({", ".join(list(data.columns))})
            SELECT * FROM RESULTS_TO_APPEND
        """
        
        print("\nquery:\n", query)
        
        job_session.sql(query).collect()

In [22]:
session.sql("""
    CREATE OR REPLACE TABLE XGBOOST_BEST_PARAMETERS (
        tuning_run_id VARCHAR,
        timestamp TIMESTAMP_NTZ,
        
        rmse_train_avg DOUBLE,
        rmse_valid_avg DOUBLE,
        relative_gap DOUBLE, 

        
        max_depth BIGINT DEFAULT 6,
        learning_rate DOUBLE DEFAULT 0.3,
        n_estimators BIGINT DEFAULT 100,
        min_child_weight BIGINT DEFAULT 1,
        subsample DOUBLE DEFAULT 1.0,

        mae_train_avg DOUBLE,
        mae_valid_avg DOUBLE,
        r2_train_avg DOUBLE,
        r2_valid_avg DOUBLE,
        rmse_train VARIANT,
        rmse_valid VARIANT,

        preprocessor_version VARCHAR, 
        should_checkpoint BOOLEAN,
        trial_id VARCHAR,
        time_total_s DOUBLE
    );
""").collect()

[Row(status='Table XGBOOST_BEST_PARAMETERS successfully created.')]

In [23]:
session.sql("""
    CREATE OR REPLACE TABLE XGBOOST_TUNING_RESULTS (
        tuning_run_id VARCHAR,
        timestamp TIMESTAMP_NTZ,
        
        rmse_train_avg DOUBLE,
        rmse_valid_avg DOUBLE,
        relative_gap DOUBLE, 

        
        max_depth BIGINT DEFAULT 6,
        learning_rate DOUBLE DEFAULT 0.3,
        n_estimators BIGINT DEFAULT 100,
        min_child_weight BIGINT DEFAULT 1,
        subsample DOUBLE DEFAULT 1.0,

        mae_train_avg DOUBLE,
        mae_valid_avg DOUBLE,
        r2_train_avg DOUBLE,
        r2_valid_avg DOUBLE,
        rmse_train VARIANT,
        rmse_valid VARIANT,

        preprocessor_version VARCHAR,
        should_checkpoint BOOLEAN,
        trial_id VARCHAR,
        time_total_s DOUBLE
    );
""").collect()

[Row(status='Table XGBOOST_TUNING_RESULTS successfully created.')]

In [24]:
#best_hyperparam(res, session)

In [27]:
session.sql("""SELECT * FROM XGBOOST_TUNING_RESULTS""").to_pandas()

Empty DataFrame
Columns: [TUNING_RUN_ID, TIMESTAMP, RMSE_TRAIN_AVG, RMSE_VALID_AVG, RELATIVE_GAP, MAX_DEPTH, LEARNING_RATE, N_ESTIMATORS, MIN_CHILD_WEIGHT, SUBSAMPLE, MAE_TRAIN_AVG, MAE_VALID_AVG, R2_TRAIN_AVG, R2_VALID_AVG, RMSE_TRAIN, RMSE_VALID, PREPROCESSOR_VERSION, SHOULD_CHECKPOINT, TRIAL_ID, TIME_TOTAL_S]
Index: []

In [28]:
session.sql("""SELECT * FROM XGBOOST_BEST_PARAMETERS""").to_pandas()

Empty DataFrame
Columns: [TUNING_RUN_ID, TIMESTAMP, RMSE_TRAIN_AVG, RMSE_VALID_AVG, RELATIVE_GAP, MAX_DEPTH, LEARNING_RATE, N_ESTIMATORS, MIN_CHILD_WEIGHT, SUBSAMPLE, MAE_TRAIN_AVG, MAE_VALID_AVG, R2_TRAIN_AVG, R2_VALID_AVG, RMSE_TRAIN, RMSE_VALID, PREPROCESSOR_VERSION, SHOULD_CHECKPOINT, TRIAL_ID, TIME_TOTAL_S]
Index: []